dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
script: python -m pytest -vv
matrix:
  include:
    - python: "3.7"
      script: flake8 github_webhook tests
    - python: "3.7"
      script: black --line-length 120 --check github_webhook tests
